from __future__ import annotations

import csv
import json
from collections import Counter, defaultdict
from typing import IO

import networkx as nx

from ..events import TransformEvent
from ..graph.attrs import parse_species_label
from .coupling import build_site_reaction_couplings
from .model import ActiveSiteEvent, ActiveSiteStateFrame, JointActiveSiteReaction


class ActiveSiteOutputWriter:
    _STATE_FIELDS = [
        "frame",
        "site_id",
        "site_family",
        "core_members",
        "intrinsic_members",
        "incorporated_members",
        "associated_members",
        "state_members",
        "intrinsic_formula",
        "intrinsic_topology",
        "incorporated_formula",
        "incorporated_topology",
        "associated_formula",
        "associated_topology",
        "state_formula",
        "state_topology",
        "state_label",
        "associated_species_labels",
        "attached_components",
        "descriptors",
    ]
    _EVENT_FIELDS = [
        "event_id",
        "frame",
        "site_id",
        "event_type",
        "old_state",
        "new_state",
        "added_members",
        "removed_members",
        "associated_species_before",
        "associated_species_after",
        "evidence_bonds",
    ]
    _JOINT_FIELDS = [
        "event_id",
        "frame",
        "site_id",
        "site_state_before",
        "site_state_after",
        "reactants",
        "products",
        "associated_species_before",
        "associated_species_after",
        "evidence_bonds",
    ]

    def __init__(self) -> None:
        self._state_fh: IO[str] | None = None
        self._state_writer: csv.DictWriter | None = None
        self._state_path: str | None = None

        self._event_fh: IO[str] | None = None
        self._event_writer: csv.DictWriter | None = None
        self._event_path: str | None = None

        self._joint_fh: IO[str] | None = None
        self._joint_writer: csv.DictWriter | None = None
        self._joint_path: str | None = None

    def _write_readme(self, out_prefix: str) -> None:
        path = f"{out_prefix}_site_outputs_README.txt"
        print(f"[write] {path}")
        text = """Active Site Outputs

This file explains the active-site CSV outputs generated by rxn_analyzer.
The output filenames still use the historical site/reactive-site naming for compatibility.

Files
- <out_prefix>_site_states.csv
  Per-frame snapshot of each active site.
- <out_prefix>_site_events.csv
  Site-centered state-change events between adjacent frames.
- <out_prefix>_joint_site_reactions.csv
  Site-centered reactions using associated species as the reaction context.
- <out_prefix>_site_reaction_coupling.csv
  Unified table linking non-host transform events with active-site state changes.
- <out_prefix>_active_site_state_counts.csv
  Summary table counting how long each active-site state appears.
- <out_prefix>_active_site_family_state_counts.csv
  Summary table counting how long each active-site family appears in each state.
- <out_prefix>_active_site_transitions.csv
  Summary table counting state-to-state transitions for each active site.
- <out_prefix>_active_site_family_transitions.csv
  Summary table counting state-to-state transitions aggregated by active-site family.
- <out_prefix>_reaction_by_active_site_state.csv
  Summary table grouping linked non-host reactions by active-site state context.
- <out_prefix>_reaction_by_active_site_family_state.csv
  Summary table grouping linked non-host reactions by active-site family/state context.
- <out_prefix>_network_site_aware.graphml
  Graph containing species, reaction, and site_state nodes in one site-aware network.

site_states.csv columns
- frame
  Frame index used by the analyzer.
- site_id
  Stable user-defined active-site identifier.
- site_family
  User-defined site family/type, for example BAS or LAS_Ga.
- core_members
  Host atoms that anchor the site identity. These should remain stable across frames.
- intrinsic_members
  Non-host atoms that are part of the site by definition or initial setup.
- incorporated_members
  Previously external atoms/fragments that are now classified as part of the current site state.
- associated_members
  External atoms/fragments still treated as associated with the site, but not incorporated into the site state.
- state_members
  Union of intrinsic_members, incorporated_members, and associated_members.
- intrinsic_formula
  Element-count formula of intrinsic_members only.
- intrinsic_topology
  Topology-aware label of intrinsic_members when recognized; otherwise close to the formula.
- incorporated_formula
  Element-count formula of incorporated_members only.
- incorporated_topology
  Topology-aware label of incorporated_members when recognized.
- associated_formula
  Element-count formula of associated_members only.
- associated_topology
  Topology-aware label of associated_members when recognized.
- state_formula
  Element-count formula of the site state body, defined as intrinsic_members + incorporated_members.
- state_topology
  Topology-aware label of the site state body, defined as intrinsic_members + incorporated_members.
- state_label
  Human-readable summary label. If associated material exists, it is appended as + assoc(...).
- associated_species_labels
  Species labels for components that remain associated with the site and are not incorporated.
- attached_components
  Atom-index tuples for associated components linked to the site.
- descriptors
  JSON dictionary with extra counters and helper fields for debugging/analysis.

site_events.csv columns
- event_id
  Unique event identifier.
- frame
  Frame where the site change is recorded.
- site_id
  Active-site identifier.
- event_type
  Currently site_state_change.
- old_state
  Previous frame state_label.
- new_state
  Current frame state_label.
- added_members
  Atoms that entered state_members compared with the previous frame.
- removed_members
  Atoms that left state_members compared with the previous frame.
- associated_species_before
  Associated species labels in the previous frame.
- associated_species_after
  Associated species labels in the current frame.
- evidence_bonds
  Bond events touching the site neighborhood in this frame.

joint_site_reactions.csv columns
- event_id
  Unique event identifier.
- frame
  Frame where the joint reaction is recorded.
- site_id
  Active-site identifier.
- site_state_before
  Previous frame state_label.
- site_state_after
  Current frame state_label.
- reactants
  Previous associated species labels, used as the reaction context.
- products
  Current associated species labels, used as the reaction context.
- associated_species_before
  Same associated-species context as reactants, kept for readability.
- associated_species_after
  Same associated-species context as products, kept for readability.
- evidence_bonds
  Bond events touching the site neighborhood in this frame.

site_reaction_coupling.csv columns
- frame
  Frame index used by the analyzer.
- site_id
  Active-site identifier.
- site_family
  Active-site family/type.
- site_state_before
  Previous frame state_label for this site.
- site_state_after
  Current frame state_label for this site.
- site_changed
  Whether an active-site state-change event exists for this frame/site pair.
- has_transform
  Whether any non-host transform event was linked to this site on this frame.
- transform_event_ids
  Linked transform event ids.
- transform_types
  Linked transform event types.
- transform_reactants
  Reactant labels aggregated from linked transform events.
- transform_products
  Product labels aggregated from linked transform events.
- associated_species_before
  Associated species labels before the event/frame transition.
- associated_species_after
  Associated species labels after the event/frame transition.
- coupling_type
  One of reaction_only_on_site, reaction_with_site_change, or site_change_only.
- link_strength
  Link confidence: strong for atom-overlap evidence, medium for species-overlap evidence, none for site-only changes.
- evidence_bonds
  Supporting bond-event evidence collected from linked transforms or site events.

active_site_state_counts.csv columns
- site_id
  Active-site identifier.
- site_family
  Active-site family/type.
- state_label
  Full state label observed in site_states.csv.
- n_frames
  Number of frames where this exact state_label appears.
- fraction_frames
  Fraction of this site's recorded frames spent in this state.
- first_frame
  First frame where this state appears.
- last_frame
  Last frame where this state appears.

active_site_family_state_counts.csv columns
- site_family
  Active-site family/type.
- state_label
  Full state label observed in site_states.csv.
- n_frames
  Number of frame/site observations in this family-level state bucket.
- fraction_frames
  Fraction of all recorded frames for this family spent in this state.
- n_unique_sites
  Number of distinct site ids contributing to this family/state bucket.
- first_frame
  First frame where this family/state bucket appears.
- last_frame
  Last frame where this family/state bucket appears.

active_site_transitions.csv columns
- site_id
  Active-site identifier.
- site_family
  Active-site family/type.
- state_before
  Previous state label.
- state_after
  New state label.
- n_events
  Number of active-site transition events with this state change.
- first_frame
  First frame where this transition is recorded.
- last_frame
  Last frame where this transition is recorded.

active_site_family_transitions.csv columns
- site_family
  Active-site family/type.
- state_before
  Previous state label.
- state_after
  New state label.
- n_events
  Number of transition events aggregated across all sites in this family.
- n_unique_sites
  Number of distinct site ids contributing to this transition bucket.
- first_frame
  First frame where this transition is recorded.
- last_frame
  Last frame where this transition is recorded.

reaction_by_active_site_state.csv columns
- site_id
  Active-site identifier.
- site_family
  Active-site family/type.
- site_state_before
  Active-site state before the linked transform(s).
- site_state_after
  Active-site state after the linked transform(s).
- coupling_type
  Whether the linked chemistry happened on a site without site change, with site change, or as a site-only change.
- reaction_signature
  Short human-readable reaction string built from grouped reactants and products.
- transform_types
  Joined transform-event types linked to this row group.
- transform_reactants
  Joined reactant labels linked to this row group.
- transform_products
  Joined product labels linked to this row group.
- n_rows
  Number of coupling rows contributing to this grouped summary.
- n_unique_frames
  Number of distinct frames contributing to this grouped summary.
- n_unique_transform_events
  Number of unique transform events in this grouped summary.
- strongest_link_strength
  Strongest link confidence seen in this group.

reaction_by_active_site_family_state.csv columns
- site_family
  Active-site family/type.
- site_state_before
  Active-site state before the linked transform(s).
- site_state_after
  Active-site state after the linked transform(s).
- coupling_type
  Whether the linked chemistry happened on a site without site change, with site change, or as a site-only change.
- reaction_signature
  Short human-readable reaction string built from grouped reactants and products.
- transform_types
  Joined transform-event types linked to this family-level row group.
- transform_reactants
  Joined reactant labels linked to this family-level row group.
- transform_products
  Joined product labels linked to this family-level row group.
- n_rows
  Number of coupling rows contributing to this grouped summary.
- n_unique_frames
  Number of distinct frames contributing to this grouped summary.
- n_unique_sites
  Number of distinct site ids contributing to this grouped summary.
- n_unique_transform_events
  Number of unique transform events in this grouped summary.
- strongest_link_strength
  Strongest link confidence seen in this group.

Reading tips
- core_members answer: which site is this?
- intrinsic_members + incorporated_members answer: what is the current site state?
- associated_members and associated_species_labels answer: what is still externally associated with the site?
- site_events.csv is the best file for site evolution.
- joint_site_reactions.csv is the best file for reaction-context interpretation.
- active_site_state_counts.csv is the best file for asking which site states dominate the trajectory.
- active_site_family_state_counts.csv is the best file for asking which state dominates a whole site family.
- active_site_transitions.csv is the best file for asking which site-state changes are most common.
- active_site_family_transitions.csv is the best file for asking which family-level state changes are most common.
- reaction_by_active_site_state.csv is the best file for asking which reactions tend to happen on which site states.
- reaction_by_active_site_family_state.csv is the best file for asking which reactions tend to happen on which site families/states.
- network_site_aware.graphml is the best graph view for seeing whether reactions happen on a site and whether the site state changes.
- In Gephi, try node labels from display_label, and inspect transform_equation, site_state_transition, coupling_type, and link_strength as custom attributes.
"""
        with open(path, "w", encoding="utf-8") as f:
            f.write(text)

    def _write_state_counts_summary(self, out_prefix: str, state_frames: list[ActiveSiteStateFrame]) -> None:
        path = f"{out_prefix}_active_site_state_counts.csv"
        print(f"[write] {path}")
        grouped: dict[tuple[str, str, str], list[int]] = defaultdict(list)
        total_by_site: Counter[tuple[str, str]] = Counter()
        for row in state_frames:
            key = (row.site_id, row.site_family, row.state_label)
            grouped[key].append(int(row.frame))
            total_by_site[(row.site_id, row.site_family)] += 1

        with open(path, "w", newline="", encoding="utf-8") as f:
            w = csv.DictWriter(
                f,
                fieldnames=[
                    "site_id",
                    "site_family",
                    "state_label",
                    "n_frames",
                    "fraction_frames",
                    "first_frame",
                    "last_frame",
                ],
            )
            w.writeheader()
            for (site_id, site_family, state_label), frames in sorted(grouped.items()):
                total = total_by_site[(site_id, site_family)]
                w.writerow(
                    {
                        "site_id": site_id,
                        "site_family": site_family,
                        "state_label": state_label,
                        "n_frames": len(frames),
                        "fraction_frames": f"{(len(frames) / total) if total else 0.0:.6f}",
                        "first_frame": min(frames),
                        "last_frame": max(frames),
                    }
                )

    def _write_family_state_counts_summary(self, out_prefix: str, state_frames: list[ActiveSiteStateFrame]) -> None:
        path = f"{out_prefix}_active_site_family_state_counts.csv"
        print(f"[write] {path}")
        grouped: dict[tuple[str, str], dict[str, object]] = defaultdict(
            lambda: {"frames": [], "sites": set()}
        )
        total_by_family: Counter[str] = Counter()
        for row in state_frames:
            key = (row.site_family, row.state_label)
            grouped[key]["frames"].append(int(row.frame))
            grouped[key]["sites"].add(row.site_id)
            total_by_family[row.site_family] += 1

        with open(path, "w", newline="", encoding="utf-8") as f:
            w = csv.DictWriter(
                f,
                fieldnames=[
                    "site_family",
                    "state_label",
                    "n_frames",
                    "fraction_frames",
                    "n_unique_sites",
                    "first_frame",
                    "last_frame",
                ],
            )
            w.writeheader()
            for (site_family, state_label), bucket in sorted(grouped.items()):
                frames = bucket["frames"]
                total = total_by_family[site_family]
                w.writerow(
                    {
                        "site_family": site_family,
                        "state_label": state_label,
                        "n_frames": len(frames),
                        "fraction_frames": f"{(len(frames) / total) if total else 0.0:.6f}",
                        "n_unique_sites": len(bucket["sites"]),
                        "first_frame": min(frames),
                        "last_frame": max(frames),
                    }
                )

    def _write_transition_summary(
        self,
        out_prefix: str,
        events: list[ActiveSiteEvent],
        state_frames: list[ActiveSiteStateFrame],
    ) -> None:
        path = f"{out_prefix}_active_site_transitions.csv"
        print(f"[write] {path}")
        grouped: dict[tuple[str, str, str, str], list[int]] = defaultdict(list)
        family_by_site: dict[str, str] = {}
        for row in state_frames:
            family_by_site.setdefault(row.site_id, row.site_family)
        for row in events:
            grouped[(row.site_id, family_by_site.get(row.site_id, ""), row.old_state, row.new_state)].append(
                int(row.frame)
            )

        with open(path, "w", newline="", encoding="utf-8") as f:
            w = csv.DictWriter(
                f,
                fieldnames=[
                    "site_id",
                    "site_family",
                    "state_before",
                    "state_after",
                    "n_events",
                    "first_frame",
                    "last_frame",
                ],
            )
            w.writeheader()
            for (site_id, site_family, state_before, state_after), frames in sorted(grouped.items()):
                w.writerow(
                    {
                        "site_id": site_id,
                        "site_family": site_family,
                        "state_before": state_before,
                        "state_after": state_after,
                        "n_events": len(frames),
                        "first_frame": min(frames),
                        "last_frame": max(frames),
                    }
                )

    def _write_family_transition_summary(
        self,
        out_prefix: str,
        events: list[ActiveSiteEvent],
        state_frames: list[ActiveSiteStateFrame],
    ) -> None:
        path = f"{out_prefix}_active_site_family_transitions.csv"
        print(f"[write] {path}")
        family_by_site: dict[str, str] = {}
        for row in state_frames:
            family_by_site.setdefault(row.site_id, row.site_family)

        grouped: dict[tuple[str, str, str], dict[str, object]] = defaultdict(
            lambda: {"frames": [], "sites": set()}
        )
        for row in events:
            key = (family_by_site.get(row.site_id, ""), row.old_state, row.new_state)
            grouped[key]["frames"].append(int(row.frame))
            grouped[key]["sites"].add(row.site_id)

        with open(path, "w", newline="", encoding="utf-8") as f:
            w = csv.DictWriter(
                f,
                fieldnames=[
                    "site_family",
                    "state_before",
                    "state_after",
                    "n_events",
                    "n_unique_sites",
                    "first_frame",
                    "last_frame",
                ],
            )
            w.writeheader()
            for (site_family, state_before, state_after), bucket in sorted(grouped.items()):
                frames = bucket["frames"]
                w.writerow(
                    {
                        "site_family": site_family,
                        "state_before": state_before,
                        "state_after": state_after,
                        "n_events": len(frames),
                        "n_unique_sites": len(bucket["sites"]),
                        "first_frame": min(frames),
                        "last_frame": max(frames),
                    }
                )

    def _write_reaction_state_summary(self, out_prefix: str, coupling_rows) -> None:
        path = f"{out_prefix}_reaction_by_active_site_state.csv"
        print(f"[write] {path}")
        strength_rank = {"none": 0, "medium": 1, "strong": 2}
        grouped: dict[tuple[str, str, str, str, str, tuple[str, ...], tuple[str, ...], tuple[str, ...]], dict[str, object]] = {}

        for row in coupling_rows:
            key = (
                row.site_id,
                row.site_family,
                row.site_state_before,
                row.site_state_after,
                row.coupling_type,
                tuple(row.transform_types),
                tuple(row.transform_reactants),
                tuple(row.transform_products),
            )
            bucket = grouped.setdefault(
                key,
                {
                    "frames": set(),
                    "transform_ids": set(),
                    "strongest": "none",
                    "count": 0,
                },
            )
            bucket["count"] = int(bucket["count"]) + 1
            bucket["frames"].add(int(row.frame))
            bucket["transform_ids"].update(int(x) for x in row.transform_event_ids)
            if strength_rank.get(row.link_strength, 0) > strength_rank.get(str(bucket["strongest"]), 0):
                bucket["strongest"] = row.link_strength

        with open(path, "w", newline="", encoding="utf-8") as f:
            w = csv.DictWriter(
                f,
                fieldnames=[
                    "site_id",
                    "site_family",
                    "site_state_before",
                    "site_state_after",
                    "coupling_type",
                    "reaction_signature",
                    "transform_types",
                    "transform_reactants",
                    "transform_products",
                    "n_rows",
                    "n_unique_frames",
                    "n_unique_transform_events",
                    "strongest_link_strength",
                ],
            )
            w.writeheader()
            for key, bucket in sorted(grouped.items()):
                (
                    site_id,
                    site_family,
                    site_state_before,
                    site_state_after,
                    coupling_type,
                    transform_types,
                    transform_reactants,
                    transform_products,
                ) = key
                reactants_joined = " + ".join(transform_reactants)
                products_joined = " + ".join(transform_products)
                w.writerow(
                    {
                        "site_id": site_id,
                        "site_family": site_family,
                        "site_state_before": site_state_before,
                        "site_state_after": site_state_after,
                        "coupling_type": coupling_type,
                        "reaction_signature": (
                            f"{reactants_joined} -> {products_joined}"
                            if (reactants_joined or products_joined)
                            else ""
                        ),
                        "transform_types": json.dumps(transform_types, ensure_ascii=False),
                        "transform_reactants": json.dumps(transform_reactants, ensure_ascii=False),
                        "transform_products": json.dumps(transform_products, ensure_ascii=False),
                        "n_rows": bucket["count"],
                        "n_unique_frames": len(bucket["frames"]),
                        "n_unique_transform_events": len(bucket["transform_ids"]),
                        "strongest_link_strength": bucket["strongest"],
                    }
                )

    def _write_family_reaction_state_summary(self, out_prefix: str, coupling_rows) -> None:
        path = f"{out_prefix}_reaction_by_active_site_family_state.csv"
        print(f"[write] {path}")
        strength_rank = {"none": 0, "medium": 1, "strong": 2}
        grouped: dict[tuple[str, str, str, str, tuple[str, ...], tuple[str, ...], tuple[str, ...]], dict[str, object]] = {}

        for row in coupling_rows:
            key = (
                row.site_family,
                row.site_state_before,
                row.site_state_after,
                row.coupling_type,
                tuple(row.transform_types),
                tuple(row.transform_reactants),
                tuple(row.transform_products),
            )
            bucket = grouped.setdefault(
                key,
                {
                    "frames": set(),
                    "sites": set(),
                    "transform_ids": set(),
                    "strongest": "none",
                    "count": 0,
                },
            )
            bucket["count"] = int(bucket["count"]) + 1
            bucket["frames"].add(int(row.frame))
            bucket["sites"].add(row.site_id)
            bucket["transform_ids"].update(int(x) for x in row.transform_event_ids)
            if strength_rank.get(row.link_strength, 0) > strength_rank.get(str(bucket["strongest"]), 0):
                bucket["strongest"] = row.link_strength

        with open(path, "w", newline="", encoding="utf-8") as f:
            w = csv.DictWriter(
                f,
                fieldnames=[
                    "site_family",
                    "site_state_before",
                    "site_state_after",
                    "coupling_type",
                    "reaction_signature",
                    "transform_types",
                    "transform_reactants",
                    "transform_products",
                    "n_rows",
                    "n_unique_frames",
                    "n_unique_sites",
                    "n_unique_transform_events",
                    "strongest_link_strength",
                ],
            )
            w.writeheader()
            for key, bucket in sorted(grouped.items()):
                (
                    site_family,
                    site_state_before,
                    site_state_after,
                    coupling_type,
                    transform_types,
                    transform_reactants,
                    transform_products,
                ) = key
                reactants_joined = " + ".join(transform_reactants)
                products_joined = " + ".join(transform_products)
                w.writerow(
                    {
                        "site_family": site_family,
                        "site_state_before": site_state_before,
                        "site_state_after": site_state_after,
                        "coupling_type": coupling_type,
                        "reaction_signature": (
                            f"{reactants_joined} -> {products_joined}"
                            if (reactants_joined or products_joined)
                            else ""
                        ),
                        "transform_types": json.dumps(transform_types, ensure_ascii=False),
                        "transform_reactants": json.dumps(transform_reactants, ensure_ascii=False),
                        "transform_products": json.dumps(transform_products, ensure_ascii=False),
                        "n_rows": bucket["count"],
                        "n_unique_frames": len(bucket["frames"]),
                        "n_unique_sites": len(bucket["sites"]),
                        "n_unique_transform_events": len(bucket["transform_ids"]),
                        "strongest_link_strength": bucket["strongest"],
                    }
                )

    def _ensure_state_writer(self, out_prefix: str) -> None:
        path = f"{out_prefix}_site_states.csv"
        if self._state_writer is not None and self._state_path == path:
            return
        self._state_path = path
        print(f"[stream] {path}")
        self._state_fh = open(path, "w", newline="", encoding="utf-8")
        self._state_writer = csv.DictWriter(self._state_fh, fieldnames=self._STATE_FIELDS)
        self._state_writer.writeheader()

    def _ensure_event_writer(self, out_prefix: str) -> None:
        path = f"{out_prefix}_site_events.csv"
        if self._event_writer is not None and self._event_path == path:
            return
        self._event_path = path
        print(f"[stream] {path}")
        self._event_fh = open(path, "w", newline="", encoding="utf-8")
        self._event_writer = csv.DictWriter(self._event_fh, fieldnames=self._EVENT_FIELDS)
        self._event_writer.writeheader()

    def _ensure_joint_writer(self, out_prefix: str) -> None:
        path = f"{out_prefix}_joint_site_reactions.csv"
        if self._joint_writer is not None and self._joint_path == path:
            return
        self._joint_path = path
        print(f"[stream] {path}")
        self._joint_fh = open(path, "w", newline="", encoding="utf-8")
        self._joint_writer = csv.DictWriter(self._joint_fh, fieldnames=self._JOINT_FIELDS)
        self._joint_writer.writeheader()

    def record_state_frames(self, out_prefix: str, rows: list[ActiveSiteStateFrame]) -> None:
        if not rows:
            return
        self._ensure_state_writer(out_prefix)
        assert self._state_writer is not None
        for row in rows:
            self._state_writer.writerow(
                {
                    "frame": row.frame,
                    "site_id": row.site_id,
                    "site_family": row.site_family,
                    "core_members": json.dumps(row.core_members, ensure_ascii=False),
                    "intrinsic_members": json.dumps(row.intrinsic_members, ensure_ascii=False),
                    "incorporated_members": json.dumps(row.incorporated_members, ensure_ascii=False),
                    "associated_members": json.dumps(row.associated_members, ensure_ascii=False),
                    "state_members": json.dumps(row.state_members, ensure_ascii=False),
                    "intrinsic_formula": row.intrinsic_formula,
                    "intrinsic_topology": row.intrinsic_topology,
                    "incorporated_formula": row.incorporated_formula,
                    "incorporated_topology": row.incorporated_topology,
                    "associated_formula": row.associated_formula,
                    "associated_topology": row.associated_topology,
                    "state_formula": row.state_formula,
                    "state_topology": row.state_topology,
                    "state_label": row.state_label,
                    "associated_species_labels": json.dumps(row.associated_species_labels, ensure_ascii=False),
                    "attached_components": json.dumps(row.attached_components, ensure_ascii=False),
                    "descriptors": json.dumps(row.descriptors, ensure_ascii=False),
                }
            )
        if self._state_fh is not None:
            self._state_fh.flush()

    def record_events(self, out_prefix: str, rows: list[ActiveSiteEvent]) -> None:
        if not rows:
            return
        self._ensure_event_writer(out_prefix)
        assert self._event_writer is not None
        for row in rows:
            self._event_writer.writerow(
                {
                    "event_id": row.event_id,
                    "frame": row.frame,
                    "site_id": row.site_id,
                    "event_type": row.event_type,
                    "old_state": row.old_state,
                    "new_state": row.new_state,
                    "added_members": json.dumps(row.added_members, ensure_ascii=False),
                    "removed_members": json.dumps(row.removed_members, ensure_ascii=False),
                    "associated_species_before": json.dumps(row.associated_species_before, ensure_ascii=False),
                    "associated_species_after": json.dumps(row.associated_species_after, ensure_ascii=False),
                    "evidence_bonds": json.dumps(row.evidence_bonds, ensure_ascii=False),
                }
            )
        if self._event_fh is not None:
            self._event_fh.flush()

    def record_joint_reactions(self, out_prefix: str, rows: list[JointActiveSiteReaction]) -> None:
        if not rows:
            return
        self._ensure_joint_writer(out_prefix)
        assert self._joint_writer is not None
        for row in rows:
            self._joint_writer.writerow(
                {
                    "event_id": row.event_id,
                    "frame": row.frame,
                    "site_id": row.site_id,
                    "site_state_before": row.site_state_before,
                    "site_state_after": row.site_state_after,
                    "reactants": json.dumps(row.reactants, ensure_ascii=False),
                    "products": json.dumps(row.products, ensure_ascii=False),
                    "associated_species_before": json.dumps(row.associated_species_before, ensure_ascii=False),
                    "associated_species_after": json.dumps(row.associated_species_after, ensure_ascii=False),
                    "evidence_bonds": json.dumps(row.evidence_bonds, ensure_ascii=False),
                }
            )
        if self._joint_fh is not None:
            self._joint_fh.flush()

    def close_streams(self) -> None:
        for fh_attr, writer_attr, path_attr in (
            ("_state_fh", "_state_writer", "_state_path"),
            ("_event_fh", "_event_writer", "_event_path"),
            ("_joint_fh", "_joint_writer", "_joint_path"),
        ):
            fh = getattr(self, fh_attr)
            if fh is not None:
                try:
                    fh.flush()
                except Exception:
                    pass
                try:
                    fh.close()
                except Exception:
                    pass
            setattr(self, fh_attr, None)
            setattr(self, writer_attr, None)
            setattr(self, path_attr, None)

    def _build_site_aware_graph(self, coupling_rows) -> nx.DiGraph:
        G = nx.DiGraph()
        species_map: dict[str, str] = {}
        site_state_map: dict[tuple[str, str], str] = {}
        reaction_map: dict[tuple, str] = {}

        def get_species_node(label: str) -> str:
            if label in species_map:
                return species_map[label]
            nid = f"s{len(species_map)}"
            species_map[label] = nid
            parsed = parse_species_label(label)
            short_label = str(parsed["short"] or parsed["formula"] or label)
            G.add_node(
                nid,
                node_type="species",
                label=short_label,
                orig_id=label,
                display_label=short_label,
                species_label=label,
                species_formula=str(parsed["formula"]),
                species_smiles=str(parsed["smiles"]),
                species_wl=str(parsed["wl"]),
                species_is_ads=bool(parsed["is_ads"]),
                species_ads_n=int(parsed["ads_n"]),
                species_ads_signature=str(parsed["ads_signature"]),
                ads_signature=str(parsed["ads_signature"]),
            )
            return nid

        def _site_body_state_label(full_state_label: str) -> str:
            raw = str(full_state_label or "").strip()
            if not raw:
                return "unknown"
            parts = raw.split(" + assoc(", 1)
            return parts[0].strip() or "unknown"

        def get_site_state_node(site_id: str, site_family: str, state_label: str) -> str:
            body_state = _site_body_state_label(state_label)
            key = (site_id, body_state)
            if key in site_state_map:
                return site_state_map[key]
            nid = f"ss{len(site_state_map)}"
            site_state_map[key] = nid
            short_label = f"{site_id}\n{body_state}"
            G.add_node(
                nid,
                node_type="site_state",
                label=short_label,
                orig_id=f"{site_id}|state={body_state}",
                display_label=short_label,
                site_id=site_id,
                site_family=site_family,
                state_label=body_state,
                site_state_label=body_state,
            )
            return nid

        def get_reaction_node(row) -> str:
            signature = (
                row.site_id,
                row.coupling_type,
                tuple(sorted(set(row.transform_types))),
                tuple(sorted(row.transform_reactants)),
                tuple(sorted(row.transform_products)),
                row.site_state_before,
                row.site_state_after,
            )
            if signature in reaction_map:
                return reaction_map[signature]
            nid = f"cr{len(reaction_map)}"
            reaction_map[signature] = nid
            if row.transform_reactants or row.transform_products:
                context_short = "rxn"
            elif row.associated_species_before or row.associated_species_after:
                context_short = "assoc"
            else:
                context_short = "site"

            if row.coupling_type == "reaction_with_site_change":
                coupling_short = "with_site_change"
            elif row.coupling_type == "reaction_only_on_site":
                coupling_short = "on_site"
            else:
                coupling_short = "site_only"

            label = f"{coupling_short}\n{context_short}"
            reactants_joined = " + ".join(row.transform_reactants) if row.transform_reactants else ""
            products_joined = " + ".join(row.transform_products) if row.transform_products else ""
            assoc_before_joined = " + ".join(row.associated_species_before) if row.associated_species_before else ""
            assoc_after_joined = " + ".join(row.associated_species_after) if row.associated_species_after else ""
            transform_types_joined = " | ".join(row.transform_types) if row.transform_types else ""
            G.add_node(
                nid,
                node_type="reaction",
                label=label,
                display_label=label,
                orig_id=json.dumps(signature, ensure_ascii=False),
                site_id=row.site_id,
                site_family=row.site_family,
                coupling_type=row.coupling_type,
                coupling_short=coupling_short,
                context_short=context_short,
                transform_types=json.dumps(row.transform_types, ensure_ascii=False),
                transform_types_joined=transform_types_joined,
                transform_event_ids=json.dumps(row.transform_event_ids, ensure_ascii=False),
                transform_reactants=json.dumps(row.transform_reactants, ensure_ascii=False),
                transform_products=json.dumps(row.transform_products, ensure_ascii=False),
                transform_reactants_joined=reactants_joined,
                transform_products_joined=products_joined,
                transform_equation=(f"{reactants_joined} -> {products_joined}" if (reactants_joined or products_joined) else ""),
                associated_species_before=json.dumps(row.associated_species_before, ensure_ascii=False),
                associated_species_after=json.dumps(row.associated_species_after, ensure_ascii=False),
                associated_species_before_joined=assoc_before_joined,
                associated_species_after_joined=assoc_after_joined,
                associated_species_transition=(f"{assoc_before_joined} -> {assoc_after_joined}" if (assoc_before_joined or assoc_after_joined) else ""),
                site_state_before=row.site_state_before,
                site_state_after=row.site_state_after,
                site_state_transition=f"{row.site_state_before} -> {row.site_state_after}",
                site_changed=bool(row.site_changed),
                has_transform=bool(row.has_transform),
                link_strength=row.link_strength,
                evidence_bonds=json.dumps(row.evidence_bonds, ensure_ascii=False),
                weight=0,
            )
            return nid

        def add_or_bump_edge(u: str, v: str, **attrs) -> None:
            if G.has_edge(u, v):
                G[u][v]["weight"] = int(G[u][v].get("weight", 0)) + 1
            else:
                G.add_edge(u, v, weight=1, **attrs)

        for row in coupling_rows:
            if row.coupling_type == "reaction_only_on_site" and not (row.transform_reactants or row.transform_products):
                continue

            rid = get_reaction_node(row)
            G.nodes[rid]["weight"] = int(G.nodes[rid].get("weight", 0)) + 1

            site_before = get_site_state_node(row.site_id, row.site_family, row.site_state_before or "unknown")
            site_after = get_site_state_node(row.site_id, row.site_family, row.site_state_after or "unknown")
            add_or_bump_edge(site_before, rid, role="site_before", coupling_type=row.coupling_type)
            add_or_bump_edge(rid, site_after, role="site_after", coupling_type=row.coupling_type)

            for sp in row.transform_reactants:
                sid = get_species_node(sp)
                add_or_bump_edge(sid, rid, role="reactant", coupling_type=row.coupling_type)
            for sp in row.transform_products:
                sid = get_species_node(sp)
                add_or_bump_edge(rid, sid, role="product", coupling_type=row.coupling_type)

        return G

    def write_all(
        self,
        out_prefix: str,
        *,
        transform_events: list[TransformEvent],
        state_frames: list[ActiveSiteStateFrame],
        events: list[ActiveSiteEvent],
        joint_reactions: list[JointActiveSiteReaction],
        streaming: bool = False,
    ) -> None:
        if not streaming:
            self.record_state_frames(out_prefix, state_frames)
            self.record_events(out_prefix, events)
            self.record_joint_reactions(out_prefix, joint_reactions)
        self.close_streams()

        coupling_rows = build_site_reaction_couplings(
            transform_events=transform_events,
            site_states=state_frames,
            site_events=events,
        )
        coupling_path = f"{out_prefix}_site_reaction_coupling.csv"
        print(f"[build] {coupling_path}")
        with open(coupling_path, "w", newline="", encoding="utf-8") as f:
            w = csv.DictWriter(
                f,
                fieldnames=[
                    "frame",
                    "site_id",
                    "site_family",
                    "site_state_before",
                    "site_state_after",
                    "site_changed",
                    "has_transform",
                    "transform_event_ids",
                    "transform_types",
                    "transform_reactants",
                    "transform_products",
                    "associated_species_before",
                    "associated_species_after",
                    "coupling_type",
                    "link_strength",
                    "evidence_bonds",
                ],
            )
            w.writeheader()
            for row in coupling_rows:
                w.writerow(
                    {
                        "frame": row.frame,
                        "site_id": row.site_id,
                        "site_family": row.site_family,
                        "site_state_before": row.site_state_before,
                        "site_state_after": row.site_state_after,
                        "site_changed": row.site_changed,
                        "has_transform": row.has_transform,
                        "transform_event_ids": json.dumps(row.transform_event_ids, ensure_ascii=False),
                        "transform_types": json.dumps(row.transform_types, ensure_ascii=False),
                        "transform_reactants": json.dumps(row.transform_reactants, ensure_ascii=False),
                        "transform_products": json.dumps(row.transform_products, ensure_ascii=False),
                        "associated_species_before": json.dumps(row.associated_species_before, ensure_ascii=False),
                        "associated_species_after": json.dumps(row.associated_species_after, ensure_ascii=False),
                        "coupling_type": row.coupling_type,
                        "link_strength": row.link_strength,
                        "evidence_bonds": json.dumps(row.evidence_bonds, ensure_ascii=False),
                    }
                )

        self._write_state_counts_summary(out_prefix, state_frames)
        self._write_family_state_counts_summary(out_prefix, state_frames)
        self._write_transition_summary(out_prefix, events, state_frames)
        self._write_family_transition_summary(out_prefix, events, state_frames)
        self._write_reaction_state_summary(out_prefix, coupling_rows)
        self._write_family_reaction_state_summary(out_prefix, coupling_rows)

        site_graph = self._build_site_aware_graph(coupling_rows)
        print(f"[build] {out_prefix}_network_site_aware.graphml")
        nx.write_graphml(site_graph, f"{out_prefix}_network_site_aware.graphml")
        self._write_readme(out_prefix)
