from __future__ import annotations

import csv
import json

from .site_model import JointReactiveSiteReaction, ReactiveSiteEvent, ReactiveSiteStateFrame


class ReactiveSiteOutputWriter:
    def _write_readme(self, out_prefix: str) -> None:
        path = f"{out_prefix}_site_outputs_README.txt"
        text = """Reactive Site Outputs

This file explains the reactive-site CSV outputs generated by rxn_analyzer.

Files
- <out_prefix>_site_states.csv
  Per-frame snapshot of each reactive site.
- <out_prefix>_site_events.csv
  Site-centered state-change events between adjacent frames.
- <out_prefix>_joint_site_reactions.csv
  Site-centered reactions using associated species as the reaction context.

site_states.csv columns
- frame
  Frame index used by the analyzer.
- site_id
  Stable user-defined reactive-site identifier.
- site_family
  User-defined site family/type, for example BAS or LAS_Ga.
- core_members
  Slab atoms that anchor the site identity. These should remain stable across frames.
- intrinsic_members
  Non-slab atoms that are part of the site by definition or initial setup.
- incorporated_members
  Previously external atoms/fragments that are now classified as part of the current site state.
- associated_members
  External atoms/fragments still treated as associated with the site, but not incorporated into the site state.
- state_members
  Union of intrinsic_members, incorporated_members, and associated_members.
- intrinsic_formula
  Element-count formula of intrinsic_members only.
- intrinsic_topology
  Topology-aware label of intrinsic_members when recognized; otherwise close to the formula.
- incorporated_formula
  Element-count formula of incorporated_members only.
- incorporated_topology
  Topology-aware label of incorporated_members when recognized.
- associated_formula
  Element-count formula of associated_members only.
- associated_topology
  Topology-aware label of associated_members when recognized.
- state_formula
  Element-count formula of the site state body, defined as intrinsic_members + incorporated_members.
- state_topology
  Topology-aware label of the site state body, defined as intrinsic_members + incorporated_members.
- state_label
  Human-readable summary label. If associated material exists, it is appended as + assoc(...).
- associated_species_labels
  Species labels for components that remain associated with the site and are not incorporated.
- attached_components
  Atom-index tuples for associated components linked to the site.
- descriptors
  JSON dictionary with extra counters and helper fields for debugging/analysis.

site_events.csv columns
- event_id
  Unique event identifier.
- frame
  Frame where the site change is recorded.
- site_id
  Reactive-site identifier.
- event_type
  Currently site_state_change.
- old_state
  Previous frame state_label.
- new_state
  Current frame state_label.
- added_members
  Atoms that entered state_members compared with the previous frame.
- removed_members
  Atoms that left state_members compared with the previous frame.
- bound_species_before
  Associated species labels in the previous frame.
- bound_species_after
  Associated species labels in the current frame.
- evidence_bonds
  Bond events touching the site neighborhood in this frame.

joint_site_reactions.csv columns
- event_id
  Unique event identifier.
- frame
  Frame where the joint reaction is recorded.
- site_id
  Reactive-site identifier.
- site_state_before
  Previous frame state_label.
- site_state_after
  Current frame state_label.
- reactants
  Previous associated species labels, used as the reaction context.
- products
  Current associated species labels, used as the reaction context.
- bound_species_before
  Same associated-species context as reactants, kept for readability.
- bound_species_after
  Same associated-species context as products, kept for readability.
- evidence_bonds
  Bond events touching the site neighborhood in this frame.

Reading tips
- core_members answer: which site is this?
- intrinsic_members + incorporated_members answer: what is the current site state?
- associated_members and associated_species_labels answer: what is still externally associated with the site?
- site_events.csv is the best file for site evolution.
- joint_site_reactions.csv is the best file for reaction-context interpretation.
"""
        with open(path, "w", encoding="utf-8") as f:
            f.write(text)

    def write_all(
        self,
        out_prefix: str,
        *,
        state_frames: list[ReactiveSiteStateFrame],
        events: list[ReactiveSiteEvent],
        joint_reactions: list[JointReactiveSiteReaction],
    ) -> None:
        states_path = f"{out_prefix}_site_states.csv"
        with open(states_path, "w", newline="", encoding="utf-8") as f:
            w = csv.DictWriter(
                f,
                fieldnames=[
                    "frame",
                    "site_id",
                    "site_family",
                    "core_members",
                    "intrinsic_members",
                    "incorporated_members",
                    "associated_members",
                    "state_members",
                    "intrinsic_formula",
                    "intrinsic_topology",
                    "incorporated_formula",
                    "incorporated_topology",
                    "associated_formula",
                    "associated_topology",
                    "state_formula",
                    "state_topology",
                    "state_label",
                    "associated_species_labels",
                    "attached_components",
                    "descriptors",
                ],
            )
            w.writeheader()
            for row in state_frames:
                w.writerow(
                    {
                        "frame": row.frame,
                        "site_id": row.site_id,
                        "site_family": row.site_family,
                        "core_members": json.dumps(row.core_members, ensure_ascii=False),
                        "intrinsic_members": json.dumps(row.intrinsic_members, ensure_ascii=False),
                        "incorporated_members": json.dumps(row.incorporated_members, ensure_ascii=False),
                        "associated_members": json.dumps(row.associated_members, ensure_ascii=False),
                        "state_members": json.dumps(row.state_members, ensure_ascii=False),
                        "intrinsic_formula": row.intrinsic_formula,
                        "intrinsic_topology": row.intrinsic_topology,
                        "incorporated_formula": row.incorporated_formula,
                        "incorporated_topology": row.incorporated_topology,
                        "associated_formula": row.associated_formula,
                        "associated_topology": row.associated_topology,
                        "state_formula": row.state_formula,
                        "state_topology": row.state_topology,
                        "state_label": row.state_label,
                        "associated_species_labels": json.dumps(row.associated_species_labels, ensure_ascii=False),
                        "attached_components": json.dumps(row.attached_components, ensure_ascii=False),
                        "descriptors": json.dumps(row.descriptors, ensure_ascii=False),
                    }
                )

        events_path = f"{out_prefix}_site_events.csv"
        with open(events_path, "w", newline="", encoding="utf-8") as f:
            w = csv.DictWriter(
                f,
                fieldnames=[
                    "event_id",
                    "frame",
                    "site_id",
                    "event_type",
                    "old_state",
                    "new_state",
                    "added_members",
                    "removed_members",
                    "bound_species_before",
                    "bound_species_after",
                    "evidence_bonds",
                ],
            )
            w.writeheader()
            for row in events:
                w.writerow(
                    {
                        "event_id": row.event_id,
                        "frame": row.frame,
                        "site_id": row.site_id,
                        "event_type": row.event_type,
                        "old_state": row.old_state,
                        "new_state": row.new_state,
                        "added_members": json.dumps(row.added_members, ensure_ascii=False),
                        "removed_members": json.dumps(row.removed_members, ensure_ascii=False),
                        "bound_species_before": json.dumps(row.bound_species_before, ensure_ascii=False),
                        "bound_species_after": json.dumps(row.bound_species_after, ensure_ascii=False),
                        "evidence_bonds": json.dumps(row.evidence_bonds, ensure_ascii=False),
                    }
                )

        joint_path = f"{out_prefix}_joint_site_reactions.csv"
        with open(joint_path, "w", newline="", encoding="utf-8") as f:
            w = csv.DictWriter(
                f,
                fieldnames=[
                    "event_id",
                    "frame",
                    "site_id",
                    "site_state_before",
                    "site_state_after",
                    "reactants",
                    "products",
                    "bound_species_before",
                    "bound_species_after",
                    "evidence_bonds",
                ],
            )
            w.writeheader()
            for row in joint_reactions:
                w.writerow(
                    {
                        "event_id": row.event_id,
                        "frame": row.frame,
                        "site_id": row.site_id,
                        "site_state_before": row.site_state_before,
                        "site_state_after": row.site_state_after,
                        "reactants": json.dumps(row.reactants, ensure_ascii=False),
                        "products": json.dumps(row.products, ensure_ascii=False),
                        "bound_species_before": json.dumps(row.bound_species_before, ensure_ascii=False),
                        "bound_species_after": json.dumps(row.bound_species_after, ensure_ascii=False),
                        "evidence_bonds": json.dumps(row.evidence_bonds, ensure_ascii=False),
                    }
                )

        self._write_readme(out_prefix)
